kubernetes_version: 1.20.4

feature_gates: "RemoveSelfLink=false"

cni: "weave"
control_plane_endpoint: "10.200.0.5:6443"
dns_domain: "cluster.local"
pod_subnet: "10.200.128.0/17"
service_subnet: "10.200.16.0/20"
